mycalendar/urls.py
from django.urls import path, include
from . import views
from django.views.generic.base import TemplateView
from accounts.forms import ContactForm
from django.contrib.auth import views as auth_views  # ログアウトに必要

app_name = 'mycalendar'

urlpatterns = [
    path(
        'month_with_schedule/',
        views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    ),
    path(
        'month_with_schedule/<int:year>/<int:month>/',
        views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    ),
    path(
        'month_with_schedule/<int:year>/<int:month>/<int:day>',
        views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    ),

    # 新規単一登録
    # path(
    #     'month_with_schedule/newadd/<int:year>/<int:month>/<int:day>',
    #     views.NewAdd.as_view(), name='NewAdd'
    # ),

    # 複数登録
    path(
        'month_with_schedule/NewMultiAdd/<int:year>/<int:month>/<int:day>',
        views.NewMultiAdd.as_view(), name='NewMultiAdd'
    ),
    # 編集
    # path(
    #     'month_with_schedule/newedit/<int:pk>',
    #     views.NewEdit.as_view(), name='NewEdit'
    # ),

    # path(
    #     'month_with_schedule/newedit/<int:year>/<int:month>/<int:day>',
    #     views.NewEdit.as_view(), name='NewEdit'
    # ),
    path(
        'month_with_schedule/NewMultiEdit/<int:year>/<int:month>/<int:day>',
        views.NewMultiEdit.as_view(), name='NewMultiEdit'
    ),
    # 入力一覧
    path(
        'DailyInputList/', views.DailyInputList.as_view(), name='DailyInputList'
    ),

    # 日次集計
    path(
        'DailySumList/', views.DailySumList.as_view(), name='DailySumList'
    ),

    # 月次集計
    path(
        'MonthlySumList/', views.MonthlySumList.as_view(), name='MonthlySumList'
    ),

    # チャート
    path(
        'Chart/', views.Chart.as_view(), name='Chart'
    ),

    # 個別グラフ
    path(
        'Graph/', views.Graph.as_view(), name='Graph'
    ),

    # プロフィール
    path(
        'profile/<int:pk>', views.ProfileView.as_view(), name='profile'
    ),

    path(
        'profile/<int:pk>/update/', views.ProfileUpdateView.as_view(), name='profile_update'
    ),

    # お問い合わせ
    path(
        'contact/', views.Contact(ContactForm), name='contact'
    ),

    # path(
    #     'contact/', views.Contact, name='contact'
    # ),

    path(
        'contact_confirm', views.ContactConfirm.as_view(), name='contact_confirm'
    ),
    path(
        'contact_send', views.ContactSend.as_view(), name='contact_send'
    ),

    # CSVエクスポート
    path(
        'SumExport/', views.SumExport, name='SumExport'
    ),

    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path(
        'mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'
    ),

    # dataTable機能
    path('datatable', TemplateView.as_view(template_name='datatable.html'), name='datatable'),
    path('schedule', views.ScheduleJsonView.as_view(), name='ScheduleJson'),
    path('print', views.PrintView.as_view(), name='print'),
    path('excel', views.ExcelView.as_view(), name='excel'),
    path('csv', views.CsvView.as_view(), name='csv'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

# 管理画面表示名変更
admin.site.site_title = 'タイトルタグ'
admin.site.site_header = 'アプリ管理サイト'
admin.site.index_title = 'メニュー'


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')), 認証関連ビュー有効化
    path('accounts/', include('allauth.urls')),  # Django-allauth利用
    path('', include('mycalendar.urls', namespace='mycalendar')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/month_with_schedule', permanent=True)),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mycalendar/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator, slug_re
from django.contrib.auth.models import AbstractUser

class LargeItem(models.Model):
    """大項目"""
    name = models.CharField(verbose_name='大項目', max_length=255)

    def __str__(self):
        return self.name

class MiddleItem(models.Model):
    """中項目"""
    name = models.CharField(verbose_name='中項目', max_length=255)
    parent = models.ForeignKey(LargeItem, verbose_name='大項目', on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class Schedule(models.Model):
    """スケジュール"""
    # LargeItem_choices = (
    #     ("HMK・旧シス対応", 'HMK・旧シス対応'),
    #     ("サービス対応", 'サービス対応'),
    #     ("抽出", '抽出'),
    #     ("PJT/案件", 'PJT/案件'),
    #     ("運用", '運用'),
    #     ("障害対応", '障害対応'),
    #     ("各種資料作成・入力", '各種資料作成・入力'),
    # )
    # LargeItem = models.CharField("大項目", max_length=50, blank=True, choices=LargeItem_choices)
    # LargeItem = models.CharField("大項目", max_length=50, blank=True)
    # MiddleItem = models.CharField("中項目", max_length=50, blank=True)
    LargeItem = models.ForeignKey(LargeItem, verbose_name='大項目',on_delete=models.PROTECT)
    MiddleItem = models.ForeignKey(MiddleItem,verbose_name='中項目',on_delete=models.PROTECT)
    SmallItem = models.CharField("小項目", max_length=50, blank=True)
    summary = models.CharField('概要', max_length=50,blank=True)
    description = models.TextField('詳細な説明', blank=True)
    memo = models.CharField('備考', max_length=50,blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    kosu = models.PositiveIntegerField('時間（分）', blank=True, default=0,validators=[RegexValidator(
        slug_re,
        '時間（分）には半角英数字のみ指定できます。',
        'invalid'
    )])
    # kosu = models.CharField('時間', max_length=50,blank=True)
    totalkosu = models.PositiveIntegerField('総時間（分）', blank=True, default=0)
    register = models.CharField('登録者', max_length=50)
    created_at = models.DateTimeField('登録日時', default=timezone.now)
    updated_at = models.DateTimeField('更新日時', auto_now=True, blank=True, null=True)

    def __str__(self):
        return str(self.LargeItem)


mycalendar/forms.py
from django import forms
from .models import Schedule


class BS4ScheduleForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm"""

    class Meta:
        model = Schedule
        fields = ('LargeItem', 'MiddleItem', 'SmallItem', 'kosu', 'summary', 'memo')  # , 'start_time', 'end_time')

        # すべてのfieldのclass属性に'form-control'を指定する
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'  # Bootstrap4対応

        # widgets = {
        #     'SmallItem': forms.CharField(attrs={
        #         'class': 'form-control',
        #     }),
        # }

        # def clean_end_time(self):
        #     kosu = self.cleaned_data['kosu']
        #     if kosu <= 1:
        #         raise forms.ValidationError(
        #             '工数は2以上で入れてね'
        #         )
        #     return kosu


# 一括新規登録用のFormSet
BS4ScheduleNewFormSet = forms.modelformset_factory(
    Schedule, form=BS4ScheduleForm, extra=5
)

# 一括編集用のFormSet
BS4ScheduleEditFormSet = forms.modelformset_factory(
    Schedule, form=BS4ScheduleForm, extra=0, can_delete=True
)

mycalendar/views.py
import locale
import logging
import csv
import datetime
from datetime import timedelta
from django.utils.decorators import method_decorator  # @method_decoratorに使用
from django.contrib.auth.decorators import login_required  # @method_decoratorに使用
from django.contrib import messages  # メッセージフレームワーク
from django.shortcuts import reverse, redirect, resolve_url
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import generic
from mycalendar.models import Schedule, LargeItem
from accounts.models import CustomUser, Profile
from .forms import BS4ScheduleForm, BS4ScheduleNewFormSet, BS4ScheduleEditFormSet
from accounts.forms import ProfileUpdateForm, ContactForm
from formtools.preview import FormPreview
from django.core.mail import send_mail
from .basecalendar import (
    MonthCalendarMixin, MonthWithScheduleMixin
)
from django.db.models import Sum
from dateutil.relativedelta import relativedelta
import pandas as pd

locale.setlocale(locale.LC_ALL, '')
logger = logging.getLogger(__name__)


# @method_decorator(login_required, name='dispatch')
# class PasswordChange(PasswordChangeView):
#     """パスワード変更ビュー"""
#     form_class = MyPasswordChangeForm
#     success_url = reverse_lazy('mycalendar:password_change_done')
#     template_name = 'account/password_change.html'
#
#
# @method_decorator(login_required, name='dispatch')
# class PasswordChangeDone(PasswordChangeDoneView):
#     """パスワード変更後ビュー"""
#     template_name = 'account/password_change_done.html'

# クラスベースビューの場合のデコレータ
@method_decorator(login_required, name='dispatch')
class MonthWithScheduleCalendar(MonthWithScheduleMixin, generic.TemplateView):
    """スケジュール付きの月間カレンダーを表示するビュー"""
    template_name = 'month_with_schedule.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        """月間カレンダー情報の入った辞書を返す"""
        context['month'] = self.get_month_calendar()
        logger.info("User:{} got month schecule.".format(str(self.request.user).split('@')[0]))
        return context


# 単一登録
# class NewAdd(MonthCalendarMixin,generic.CreateView):
#     template_name = 'newadd.html'
#     form_class = BS4ScheduleForm
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         # context['week'] = self.get_week_calendar()
#         context['month'] = self.get_month_calendar()
#         return context
#
#     def form_valid(self, form):
#         month = self.kwargs.get('month')
#         year = self.kwargs.get('year')
#         day = self.kwargs.get('day')
#         if month and year and day:
#             date = datetime.date(year=int(year), month=int(month), day=int(day))
#         else:
#             date = datetime.date.today()
#         schedule = form.save(commit=False)
#         schedule.register = self.request.user
#         schedule.date = date
#         schedule.save()
#         return redirect('mycalendar:month_with_schedule', year=date.year, month=date.month, day=date.day)


@method_decorator(login_required, name='dispatch')
class NewMultiAdd(MonthCalendarMixin, generic.FormView):
    """一括登録・登録後表示"""
    template_name = 'multiAdd.html'
    # form_class = BS4ScheduleFormSet
    success_url = reverse_lazy('mycalendar:month_with_schedule')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['week'] = self.get_week_calendar()
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        indate = str(year) + '年' + str(month) + '月' + str(day) + '日'
        date = datetime.date(year=int(year), month=int(month), day=int(day))
        context['indate'] = indate
        context['month'] = self.get_month_calendar()
        context['LargeItem'] = LargeItem.objects.all()
        context['registered'] = Schedule.objects.filter(date=date).filter(register=str(self.request.user).split('@')[0])
        try:
            totalkosu = Schedule.objects.filter(date=date).filter(register=str(self.request.user).split('@')[0]).first()
            context['totalkosu'] = totalkosu
        except:
            context['totalkosu'] = 0
        return context

    def get_form(self, form_class=None):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = str(year) + '-' + str(month) + '-' + str(day)
        return BS4ScheduleNewFormSet(self.request.POST or None,
                                     queryset=Schedule.objects.none())

    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        # for fm in form:
        #     schedule = fm.save(commit=False)
        #     # schedule.register = self.request.user
        #     schedule.date = date
        #     schedule.save()
        # return redirect('mycalendar:month_with_schedule', year=date.year, month=date.month, day=date.day)
        # return super().form_valid(form)

        instances = form.save(commit=False)
        # 新たに作成されたscheduleと更新されたscheduleを取り出して、新規作成or更新処理
        for schedule in instances:
            schedule.register = str(self.request.user).split('@')[0]
            schedule.date = date
            schedule.save()
        # 総時間をkosuを合計してカラムに登録
        kosuBydate = Schedule.objects.filter(date=date).values('date', 'register').annotate(totalkosu=Sum('kosu'))
        for i in kosuBydate:
            if i['register'] == str(self.request.user).split('@')[0]:
                total = i['totalkosu']

        for row in Schedule.objects.filter(date=date).filter(register=str(self.request.user).split('@')[0]):
            row.totalkosu = int(total)
            row.save()

        logger.info("User:{} MultiAdd in {} successfully.".format(str(self.request.user), date))
        messages.success(self.request, date.strftime('%Y年%m月%d日') + "に新規登録しました。")
        # return redirect('mycalendar:month_with_schedule', year=date.year, month=date.month, day=date.day)
        return redirect('mycalendar:NewMultiAdd', year=date.year, month=date.month, day=date.day)


@method_decorator(login_required, name='dispatch')
class NewMultiEdit(MonthCalendarMixin, generic.FormView):
    """一括編集機能"""
    template_name = 'multiEdit.html'
    # form_class = BS4ScheduleFormSet
    success_url = reverse_lazy('mycalendar:month_with_schedule')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['week'] = self.get_week_calendar()
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        indate = str(year) + '年' + str(month) + '月' + str(day) + '日'
        context['month'] = self.get_month_calendar()
        context['indate'] = indate
        context['LargeItem'] = LargeItem.objects.all()
        return context

    def get_form(self, form_class=None):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = str(year) + '-' + str(month) + '-' + str(day)
        return BS4ScheduleEditFormSet(self.request.POST or None,
                                      queryset=Schedule.objects.filter(date=date,
                                                                       register=str(self.request.user).split('@')[0]))

        # def form_valid(self, form):
        #     month = self.kwargs.get('month')
        #     year = self.kwargs.get('year')
        #     day = self.kwargs.get('day')
        #     if month and year and day:
        #         date = datetime.date(year=int(year), month=int(month), day=int(day))
        #     else:
        #         date = datetime.date.today()
        #     for fm in form:
        #         schedule = fm.save(commit=False)
        #         # schedule.register = self.request.user
        #         schedule.date = date
        #         schedule.save()
        #     return redirect('mycalendar:month_with_schedule', year=date.year, month=date.month, day=date.day)
        # return super().form_valid(form)

    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        # instancesは、新たに作成されたscheduleと更新されたscheduleが入ったリスト
        instances = form.save(commit=False)

        # まず、削除チェックがついたscheduleを取り出して削除
        for schedule in form.deleted_objects:
            schedule.delete()

        total = 0
        # 新たに作成されたscheduleと更新されたscheduleを取り出して、新規作成or更新処理
        for schedule in instances:
            schedule.register = str(self.request.user).split('@')[0]
            schedule.date = date
            schedule.save()

        kosuBydate = Schedule.objects.filter(date=date).values('date', 'register').annotate(totalkosu=Sum('kosu'))
        for i in kosuBydate:
            if i['register'] == str(self.request.user).split('@')[0]:
                total = i['totalkosu']

        for row in Schedule.objects.filter(date=date).filter(register=str(self.request.user).split('@')[0]):
            row.totalkosu = int(total)
            row.save()
        messages.success(self.request, date.strftime('%Y年%m月%d日') + "を更新しました。")
        logger.info("User:{} MultiEdit in {} successfully.".format(str(self.request.user), date))
        return redirect('mycalendar:month_with_schedule', year=date.year, month=date.month, day=date.day)
        # return super().form_valid(form)

templates/MonthlySumList.html
{% extends 'base.html' %}
<head>
    {% block title %}月次集計一覧{% endblock %}
</head>

{% block extracss %}

{% endblock %}

<body>
{% block contents %}
    <div class="col-md-12 main">
        <h4 class="page-header">月次集計一覧</h4>
        <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'mycalendar:MonthlySumList' %}">
            <input class="form-control mr-sm-2" type="month" min="2018-01" max="201-12" aria-label="Search"
                   name="keyword1">
            <input class="form-control mr-sm-2" type="text" aria-label="Search" name="keyword2">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <div class="table-sm">
            <table class="table table-bordered table-hover">
                <thead>
                <tr class="table-primary">
                    <th>期間</th>
                    <th>大項目</th>
                    <th>総工数</th>
                    <th>登録者</th>
                </tr>
                </thead>
                <tbody>
                {% for sum in MonthlySumList %}
                    <tr>
                        <td>{{ year_month }}</td>
                        <td>{{ sum.LargeItem__name }}</td>
                        <td>{{ sum.MonthlySum }}</td>
                        <td>{{ sum.register }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% csrf_token %}
        </div>
        <div class="col-md-3">
            <span>集計データを元にグラフ生成</span><br>
            <form class="form-inline" action="{% url 'mycalendar:Graph' %}" method="get">
                <input class="form-control mr-sm-2" type="month" min="2018-01" max="2019-12" aria-label="Search"
                       aria-label="Search"
                       name="graph1">
                <input class="form-control mr-sm-2" type="text" aria-label="Search" name="graph2">
                <button class="btn btn-success my-2 my-sm-0" type="submit">グラフ描画</button>
            </form>
            <a href="{% url 'mycalendar:Chart' %}" class="btn btn-success">oldグラフ描画</a><br>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div>
                        <canvas id="PieChart1"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <span>集計データをCSV出力</span><br>
            <form action="{% url 'mycalendar:SumExport' %}" method="get">
                <input class="form-control mr-sm-2" type="month" min="2018-01" max="2019-12" aria-label="Search"
                       name="csvexport">
                <button class="btn btn-primary " type="submit">CSV出力</button>
            </form>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>
    <script>
    {% block extrajs %}
        var ctx = document.getElementById("PieChart1").getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: [{% for index, row in df.iterrows %}
                    '{{ row.LargeItemLabel }}',
                {% endfor %}],
                datasets: [{
                    backgroundColor: [
                        "#2ecc71",
                        "#3498db",
                        "#95a5a6",
                        "#9b59b6",
                        "#f1c40f",
                        "#e74c3c",
                        "#34495e"
                    ],
                    data: [{% for index, row in df.iterrows %}
                        {{ row.kosu }},
                    {% endfor %}],
                }]
            },
            options: {
                title: {
                    display: true,
                    position: 'bottom',
                    fontSize: 15,
                    {#text: 'admin'#}
                }
            }
        });
    {% endblock %}
{% endblock %}
</body>

templates/base.html
{#{% load staticfiles %}#}
{# Load the tag library #}
{% load static %}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{#{% bootstrap_messages %}#}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap4.1.0 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
    {% block extrahead %}{% endblock %}
</head>

<style>
    body {
        background-color: #edf4fb;
    }

    table {
        table-layout: fixed;
    }

    .table th {
        border: 1px solid #b4b6b8;
    }

    .table tr {
        border: 1px solid #b4b6b8;
    }

    .table td {
        border: 1px solid #b4b6b8;
    }

    {% block extracss %}{% endblock %}

</style>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="{% url 'mycalendar:month_with_schedule' %}">作業工数管理（仮）</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'mycalendar:DailyInputList' %}">入力一覧</a>
                </li>
                {#            {% if user.is_staff %}#}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'mycalendar:DailySumList' %}">日次集計一覧</a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'mycalendar:MonthlySumList' %}">月次集計一覧</a>
                </li>
                {#            {% endif %}#}
                <li>
                    <a class="nav-item nav-link active" href="{% url 'mycalendar:Graph' %}">グラフ表示</a>
                </li>
                <li>
                    <a class="nav-item nav-link active" href="{% url 'mycalendar:datatable' %}">全登録データ</a>
                </li>
                <li>
                    <a class="nav-item nav-link active" href="{% url 'mycalendar:profile' user.pk %}">プロフィール</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>
                </li>
                </ul>
                <span style="color:white;" class="navbar-text navbar-right">ログイン中：{{ user.get_username }}</span>
            {% endif %}
        {% block navbar %}
        {% endblock %}
    </div>
</nav>

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<div class="container-fluid">
    {% block contents %}
    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>


<!-- jsを書く場所 -->
<script>{% block extrajs %}{% endblock %}</script>

</body>
</html>

templates/month.html
{% extends './base.html' %}
{% block content %}

<a href="{% url 'sampleapp:month' month.previous.year month.previous.month %}">前月</a>
{{ month.current | date:"Y年m月" }}
<a href="{% url 'sampleapp:month' month.next.year month.next.month %}">次月</a>
<table class="table">
  <thead>
    <tr>
      {% for w in month.week_names %}
        <th>{{ w }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for week in month.days %}
      <tr>
        {% for day in week %}
          {% if month.now == day %}
            <td class="table-success">
          {% else %}
            <td>
          {% endif %}
          {% if month.current.month != day.month %}
            {{ day | date:"m/d" }}
          {% else %}
            {{ day.day }}
          {% endif %}
          </td>
        {% endfor %}
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/mycalendar.html
{% extends './base.html' %}
{% block content %}
<div class="row">
  <div class="col-md-3">
    {% include 'sampleapp/widgets/month.html' %}
    <hr>
    <form action="" method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
            <div class="col-sm-8">
              {{ field }}
              {{ field.errors }}
            </div>
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-block">送信</button>
    </form>
  </div>
  <div class="col-md-9">
    {% include 'sampleapp/widgets/week.html' %}
  </div>
</div>
{% endblock %}


{% block extrajs %}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
<script>
    $(function() {
        // Bootstrap4 tooltip
        $('[data-toggle="tooltip"]').tooltip('show');

        // timedropper
        $( "#id_start_time" ).timeDropper({
            format: "H:mm",
            setCurrentTime: false,
        });
        $( "#id_end_time" ).timeDropper({
            format: "H:mm",
            setCurrentTime: false,
        });
    });
</script>
{% endblock %}